var colors = {
	'Renaissance': '#212D8B',
	'Baroque Italy': '#3366FF',
	'Baroque France': '#6633FF',
	'Baroque Europe': '#CC33FF',
	'Late Baroque / Rococo': '#FF33CC',
	'French Rationalism': '#33CCFF',
	'Archaeology and Antiques': '#003DF5',
	'Visionary Architecture': '#002EB8',
	'Picturesque': '#FF3366',
	'France: Revolution and the Public': '#33FFCC',
	'Neo-Gothic': '#B88A00',
	'Neoclassicism: Nationalism': '#F5B800',
	'Industrial Revolution': '#FF6633',
	'Reactions Against Industrialization': '#33FF66',
	'Vienna Secession / Ringstrasse': '#66FF33',
	'Countering Ornamentation': '#CCFF33',
	'Arts & Crafts / Art Nouveau': '#FFCC33',
	'First Gen Chicago School': '#D2CA58',
};